Update ZAP to v2023.04.05-nightly
The current Matter SDK examples are failing to build with an error like this:

```
cd /var/chip/examples/lighting-app/nrfconnect/build && /var/chip/scripts/tools/zap/generate.py --no-prettify-output --templates /var/chip/src/app/zap-templates/app-templates.json --output-dir /var/chip/examples/lighting-app/nrfconnect/build/gen/app-zapgen/zapgen/app-templates/zap-generated --lock-file /var/chip/examples/lighting-app/nrfconnect/build/zap_gen.lock --parallel /var/chip/examples/lighting-app/nrfconnect/../lighting-common/lighting-app.zap
Searching for zcl file from /var/chip/examples/lighting-app/nrfconnect/../lighting-common/lighting-app.zap
Checking ZAP from ['/var/zap/v2023.01.19-nightly/zap-cli']:
  !!! Version validation failed: required at least 2023.4.5, got 2023.1.19 instead
[127/532] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/cbprintf_complete.c.obj
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake --build /var/chip/examples/lighting-app/nrfconnect/build
```

I got an "authorization failed" error when trying to build the image so I
wasn't able to actually test this change.